services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_backend:/mlflow
    command: mlflow server --backend-store-uri /mlflow --host 0.0.0.0 --port 5000

volumes:
  mlflow_backend:
